title: "Your website title"
url: "https://monsoonmalabar.com/midhun"
email: "midhunmithu1111@gmail.com"
markdown: kramdown
mobile: 
country: 
currency_code: 
paypal_email: 
razorpay_key: 
location: 
category: "Kirana Store, FMCG & Grocery"
sass:
  sass_dir: _sass
  style: compressed
collections:
  products:
    output: true
defaults:
  - scope:
      type: posts
    values:
      layout: product
  - scope:
      type: products
    values:
      layout: post
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
encoding: UTF-8
permalink: /products/:title/
paginate: 10
permalink: /:categories/:title/
paginate_path: 'page/:num/'
favicon: "https://monsoonmalabar.com/midhun/logo.png"
paypal: 
fb_appid: 
analytics: 
adsense: 